[[redirects]]
  from = "https://accounts.kakao.com/*"
  to = "https://surbay-sprint.netlify.app/kakao-oauth"
  status = 200
  force = true
  query = {code = ":code"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200