[[redirects]]
  from = "https://accounts.kakao.com/*"
  to = "kakao-oauth"
  status = 200
  force = true
  query = {code = ":code"}

[[redirects]]
  from = "*"
  to = "redirect"
  status = 200
  force = true
  query = {voteId = ":voteId"}

[[redirects]]
  from = "/*"
  to = "/"
  status = 200